export const CHAT_HISTORY_KEY = 'htw-chat-history';
export const SETTINGS_KEY = 'htw-chat-settings';

export const defaultSettings = {
    uiLanguage: 'de',
    theme: 'system',
    accentColor: '#EC6608',
    fontSize: 'medium',
    layoutDensity: 'standard',
    animationSpeed: 'normal',
    homeScreenIcon: '/assets/images/smoky_klein.png',
    saveHistory: true,
    autoDelete: '0',
    tts: false,
    contrastMode: false,
    keyboardNav: false,
    sendWithEnter: true,
    timestampFormat: '24h',
    maxChatWidth: 'default',
};

export const i18n = {
    de: {
        settings_title: "Einstellungen",
        settings_ui_language: "Sprache der Einstellungen",
        section_behavior_title: "Funktionalität & Verhalten",
        setting_send_with_enter: "Nachricht mit Enter senden",
        setting_notification_sound: "Benachrichtigungston bei neuer Nachricht",
        section_design_title: "Design & Darstellung",
        setting_theme: "Design-Modus",
        theme_system: "System",
        theme_light: "Hell",
        theme_dark: "Dunkel",
        setting_accent_color: "Akzentfarbe",
        setting_font_size: "Schriftgröße",
        font_size_small: "Klein",
        font_size_medium: "Mittel",
        font_size_large: "Groß",
        setting_layout_density: "Layoutdichte",
        layout_density_compact: "Kompakt",
        layout_density_standard: "Standard",
        layout_density_spacious: "Großzügig",
        setting_animation_speed: "Animationsdauer",
        animation_speed_normal: "Normal",
        animation_speed_reduced: "Reduziert",
        animation_speed_none: "Keine",
        setting_timestamp_format: "Zeitstempel-Format",
        timestamp_format_24h: "24 Stunden",
        timestamp_format_12h: "12 Stunden (AM/PM)",
        setting_max_chat_width: "Maximale Chat-Breite",
        max_chat_width_default: "Standard (1350px)",
        max_chat_width_medium: "Mittel (1000px)",
        max_chat_width_small: "Klein (800px)",
        max_chat_width_full: "Unbegrenzt",
        setting_home_screen_icon: "Home-Bildschirm-Icon",
        section_accessibility_title: "Barrierefreiheit",
        setting_tts: "Vorlesefunktion aktivieren",
        setting_contrast_mode: "Kontrastmodus aktivieren",
        setting_keyboard_nav: "Tastaturnavigation verbessern",
        section_privacy_title: "Datenschutz & Daten",
        setting_save_history: "Verlauf speichern",
        setting_auto_delete: "Automatisches Löschen nach",
        auto_delete_never: "Nie",
        auto_delete_1_day: "1 Tag",
        auto_delete_7_days: "7 Tagen",
        auto_delete_30_days: "30 Tagen",
        export_history_label: "Verlauf exportieren",
        export_history_button: "Gesamten Verlauf herunterladen",
        import_history_label: "Verlauf importieren",
        import_history_button: "Verlauf aus Datei hochladen",
        delete_all_chats_label: "Alle Chats löschen",
        delete_all_chats_button: "Jetzt löschen",
        section_api_title: "API-Nutzung",
        api_key_label: "Persönlicher API-Schlüssel",
        api_key_status_not_set: "Nicht konfiguriert",
        api_key_configure_button: "Konfigurieren & Limits aufheben",
        reset_settings_button: "Auf Standard zurücksetzen",
        save_settings_button: "Speichern & Anwenden",
    },
    en: {
        settings_title: "Settings",
        settings_ui_language: "Settings Language",
        section_behavior_title: "Functionality & Behavior",
        setting_send_with_enter: "Send message with Enter",
        setting_notification_sound: "Notification sound on new message",
        section_design_title: "Design & Appearance",
        setting_theme: "Theme Mode",
        theme_system: "System",
        theme_light: "Light",
        theme_dark: "Dark",
        setting_accent_color: "Accent Color",
        setting_font_size: "Font Size",
        font_size_small: "Small",
        font_size_medium: "Medium",
        font_size_large: "Large",
        setting_layout_density: "Layout Density",
        layout_density_compact: "Compact",
        layout_density_standard: "Standard",
        layout_density_spacious: "Spacious",
        setting_animation_speed: "Animation Speed",
        animation_speed_normal: "Normal",
        animation_speed_reduced: "Reduced",
        animation_speed_none: "None",
        setting_timestamp_format: "Timestamp Format",
        timestamp_format_24h: "24-hour",
        timestamp_format_12h: "12-hour (AM/PM)",
        setting_max_chat_width: "Maximum Chat Width",
        max_chat_width_default: "Default (1350px)",
        max_chat_width_medium: "Medium (1000px)",
        max_chat_width_small: "Small (800px)",
        max_chat_width_full: "Unlimited",
        setting_home_screen_icon: "Home Screen Icon",
        section_accessibility_title: "Accessibility",
        setting_tts: "Enable Text-to-Speech",
        setting_contrast_mode: "Enable High Contrast Mode",
        setting_keyboard_nav: "Improve Keyboard Navigation",
        section_privacy_title: "Privacy & Data",
        setting_save_history: "Save History",
        setting_auto_delete: "Auto-delete after",
        auto_delete_never: "Never",
        auto_delete_1_day: "1 day",
        auto_delete_7_days: "7 days",
        auto_delete_30_days: "30 days",
        export_history_label: "Export History",
        export_history_button: "Download entire history",
        import_history_label: "Import History",
        import_history_button: "Upload history from file",
        delete_all_chats_label: "Delete All Chats",
        delete_all_chats_button: "Delete Now",
        section_api_title: "API Usage",
        api_key_label: "Personal API Key",
        api_key_status_not_set: "Not configured",
        api_key_configure_button: "Configure & Lift Limits",
        reset_settings_button: "Reset to Default",
        save_settings_button: "Save & Apply",
    }
};

export const i18n_feedback = {
    de: {
        feedback_title: "Feedback geben",
        feedback_language: "Sprache des Formulars",
        feedback_description: "Ist Ihnen ein Fehler aufgefallen oder haben Sie einen Verbesserungsvorschlag? Wir freuen uns über Ihre Rückmeldung!",
        feedback_message: "Ihre Nachricht",
        feedback_message_placeholder: "Beschreiben Sie hier Ihr Anliegen...",
        feedback_email: "E-Mail (optional)",
        feedback_captcha: "Sicherheitsfrage",
        feedback_captcha_placeholder: "Antwort",
        feedback_send: "Senden",
    },
    en: {
        feedback_title: "Give Feedback",
        feedback_language: "Form Language",
        feedback_description: "Have you noticed an error or do you have a suggestion for improvement? We look forward to your feedback!",
        feedback_message: "Your Message",
        feedback_message_placeholder: "Describe your issue here...",
        feedback_email: "Email (optional)",
        feedback_captcha: "Security Question",
        feedback_captcha_placeholder: "Answer",
        feedback_send: "Send",
    }
};